init
Marynok/Martyuk_Labs pull request #1
Opened 2021-04-11 15:03 UTC by Marynok

First lab was created

2021-04-14 09:38 UTC, serhii-shkodenko requested changes
Исправьте эти замечания, пожалуйста.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +        decimal saleForSimmilarStreet = 15;
Такие переменные лучше всего делать константами.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                while (list[i].MoveNext())
Попытайся избегать перебора коллекции во время перебора другой. Цикл в цикле это не очень хорошая идея.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +       public int CheckCount(params IEnumerator[] list)
Для того чтобы проверить количество элементов в массиве есть метод `Enumerable.Count()`.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                foreach (KeyValuePair<Regex, decimal> s in sales)
Снова цикл в цикле. Это не очень хорошая идея.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                    MatchCollection m = s.Key.Matches(str);
Используй неявное определение типа для переменных с помощью var. Есть [соответствующая конвенция](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#implicitly-typed-local-variables).

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +        public void ChildrensChecks(IEnumerable<int> persons, decimal[] perCentSale, PerCentSales type)
Переменная `perCentSale` должна иметь в имени указание на множественное число, потому что она представляет массив.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +        public void ChildrensChecks(IEnumerable<int> persons, decimal[] perCentSale, PerCentSales type)
Тип `PerCentSales` можно перевести как "продажи на каждый цент". Стоит избегать двусмысленностей в именах.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +        public void ChildrensChecks(IEnumerable<int> persons, decimal[] perCentSale, PerCentSales type)
Имя метода наталкивает на то, что он будет что-то проверять, но тип возвращаемого значения у него `void`. Кроме того, он ничего не проверяет, а добавляет элементы в массив. В методе ты делаешь не то, что ты декларируешь.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +        public void NextStreetChecks(IEnumerable<string> streets, decimal[] perCentSale)
Имя метода наталкивает на то, что он будет что-то проверять, но тип возвращаемого значения у него void. В методе ты делаешь не то, что ты декларируешь.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                MatchCollection m = symbol.Matches(str[str.Length - 1]);
Используй неявное определение типа для переменных с помощью var. Есть [соответствующая конвенция](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#implicitly-typed-local-variables).

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                    foreach (Match match in m)
Снова цикл в цикле. Этого можно избежать.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +        public void finalPrice(IEnumerable<string> currencies, IEnumerable<decimal> prices, decimal[] fPrice,
Методы в C# называются в `CamelCase`. Метод должен содержать глагол. Подробнее об этом [можно почитать здесь](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +            var currenc = currencies.GetEnumerator();
Опечатка должно быть `currency`.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +        public decimal finalSumPrice(IEnumerable<string> currencies,  decimal[] fPrice,
Методы в C# называются в `CamelCase`. Метод должен содержать глагол. Подробнее об этом [можно почитать здесь](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods).

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CurrencyTranslation.cs
> +    static class CurrencyTranslation
Ввидимо имелось в виду не `CurrencyTranslation`, а `CurrencyExchangeConvertation`.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CurrencyTranslation.cs
> +        static public string value = "USD";
Публичные поля в C# рассмативаются как в качествве сомнительной практики. Ее следует избегать.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/CurrencyTranslation.cs
> +        static Dictionary<String, decimal> kyrs = new Dictionary<String, decimal> { { "EUR", 1.19m } };
Транслитерированное имя. Имена всех идентификаторов должны быть на английском.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/HomeWork.cs
> +            //start
Этот комментарий не проясняет код. Его можно удалить.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/HomeWork.cs
> +                //
Этот комментарий не проясняет код. Его можно удалить.

2021-04-14 09:38 UTC, serhii-shkodenko commented on lab_1/lab_1.csproj
> +    <TargetFramework>netcoreapp3.1</TargetFramework>
Проект должен быть на .NET5.

2021-04-16 13:36 UTC, serhii-shkodenko requested changes
Поправь эти замечания и следующим шагом будет апрув.

2021-04-16 13:36 UTC, serhii-shkodenko commented on lab_1/lab_1.csproj
> +    <NoWin32Manifest>true</NoWin32Manifest>
В документации сказано, что [This property applies only to Visual Studio projects targeting Windows Vista](https://docs.microsoft.com/en-us/visualstudio/msbuild/common-msbuild-project-properties?view=vs-2019). Кроме того, это свойство применяется [только для .NET Framework](https://docs.microsoft.com/en-us/dotnet/api/microsoft.build.tasks.managedcompiler.nowin32manifest?view=netframework-4.8).

2021-04-16 13:36 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +            Infants = 50,
Да, в .NET типы enum достаточно ограничены, поэтому твоя реализация достаточно спорная. Более оптимальным здесь было бы использовать, например, `Dictionary<enum, decimal>`. Есть также библиотеки, который позволяют сделать то, что ты хочешь, например, [Smart Enum](https://github.com/ardalis/SmartEnum). Сейчас ничего менять не нужно, однако в будущем, пожалуйста, учти этот момент.

2021-04-16 13:36 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                    sales.Where(
Согласо C# code styles, это выражение лучше было бы оформить так:
```
   sales.Where(sale => streets.ElementAt(i).Contains(sale.Key))
        .Select(sale => sale.Value)
        .Sum();
```

2021-04-16 13:36 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                currentStr = String.Concat(m);
Похоже, что твоя логика определяет штат, а не улицу. А по условиям задания нужно сравнивать улицы.
![state_instead](https://user-images.githubusercontent.com/69808191/115030771-22d98900-9ed0-11eb-9ce3-2946ad18728b.jpg)

2021-04-16 13:36 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +            Regex symbol = new Regex(@"(\D*)");
Используй неявное определение типов переменных с помощью `var`.

2021-04-16 13:36 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +            Regex space = new Regex(@"(\S*)");
Используй неявное определение типов переменных с помощью `var`.

2021-04-16 13:36 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                if (currencies.ElementAt(i) != CurrencyExchangeConvertation.Value)
Ты здесь и чуть ниже два раза конвертируешь цены. В одном случае, ты конвертируешь в евро скидку, учитываешь ее в цене. Потом ниже, ты переводишь весь массив в одну валюту. Лучше сразу перевести цены в доллары, и потом применять к ним скидки, раз они все по условияю задачи в долларах. Таким образом ты избавишься от одного цикла.

2021-04-16 14:13 UTC, Marynok commented on lab_1/CheckSales.cs
> +                if (currencies.ElementAt(i) != CurrencyExchangeConvertation.Value)
Просто в задании сказано: «Стоимость доставки по адресу может указываться как в евро, так и в долларах» и у меня есть массив стоимостей доставки после скидок из за этого конвертация происходит дважды. С другой стороны задание этого не требует.. могу переделать .?

2021-04-16 14:19 UTC, serhii-shkodenko commented on lab_1/CheckSales.cs
> +                if (currencies.ElementAt(i) != CurrencyExchangeConvertation.Value)
Все верно, цены могут быть в двух валютах. Однако фиксированные скидки указаны только в долларах. Поэтому для сокращения расчетов, достаточно один раз перевести цены в доллары. Да, будет лучше поправить.

2021-04-17 21:16 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-04-19 08:13 UTC, merged