init lb_2
Marynok/Martyuk_Labs pull request #2
Opened 2021-04-17 17:45 UTC by Marynok

Second task was created

2021-04-17 20:26 UTC, serhii-shkodenko requested changes

2021-04-17 20:26 UTC, serhii-shkodenko commented on DeliveryService/models/Address.cs
> +namespace DeliveryService.models
Согласно [конвенции](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces), в нейспейсах используются имена в `PascalCase`.

2021-04-17 20:26 UTC, serhii-shkodenko commented on DeliveryService/models/Client.cs
> +        public List<Order> Orders { get; set; }
Лучше использовать более абстрактные типы для контрактов. В данном случае - `IList` вместо `List`. Просмотри, пожалуйста, все классы.

2021-04-17 20:26 UTC, serhii-shkodenko commented on DeliveryService/models/FoodType.cs
> +    public enum FoodType
Это не очень хорошая идея так сильно себя ограничивать в плане доступных продуктов. Лучше сделать для этого отдельный тип.

2021-04-18 14:31 UTC, Marynok commented on DeliveryService/models/FoodType.cs
> +    public enum FoodType
Я еще хотела спросить, у меня есть сущности Street, Address и HouseNumber. Стоит ли номер дома выносить как отдельную сущность в данном случае?

2021-04-18 14:37 UTC, serhii-shkodenko commented on DeliveryService/models/FoodType.cs
> +    public enum FoodType
Хорошо, что ты спросила. Я бы не выделял ни улицу, ни номер дома в отдельные типы. Адреса вполне достаточно. И улицу и номер дома лучше сделать строковыми типами (номер дома может быть типа 234/b, например).

2021-04-18 14:48 UTC, serhii-shkodenko requested changes

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/Food.cs
> +        public string FoodName { get; set; }
Достаточно будет просто назвать `Name`. Из контекста ясно, что это свойство относится именно к продукту.

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/Food.cs
> +        public Company FoodCompany { get; set; }
Достаточно будет просто назвать `Company`. Из контекста ясно, что это свойство относится именно к продукту. И если имеется в виду "производитель", то лучше назвать свойство `Manufacturer`.

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/HouseNumber.cs
> +    public class HouseNumber: Model
Избыточная модель, ее лучше удалить.

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
У тебя есть список продуктов `Foods`, там ты сможешь узнать количество. Это свойство избыточно.

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/Order.cs
> +        public Address OrderAddress { get; set; }
Достаточно будет просто назвать `Address`. Из контекста ясно, что это свойство относится именно к заказу.

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/Street.cs
> +    public class Street: Model
Избыточная сущность, ее лучше удалить.

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/baseModel/Model.cs
> +
Лишняя строка.

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/Company.cs
> +        public Address CompanyAddress { get; set; }
Достаточно будет просто назвать `Address`. Из контекста ясно, что это свойство относится именно к компании.

2021-04-18 14:48 UTC, serhii-shkodenko commented on DeliveryService/models/Company.cs
> +    public class Company: Model
Если имеется в виду "производитель", то лучше назвать тип `Manufacturer`.

2021-04-18 14:57 UTC, Marynok commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
Ну и общую цену я могу узнать тем же путем, Price  тоже избыточно?

2021-04-18 14:59 UTC, Marynok commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
А не смогу, я поняла

2021-04-18 15:03 UTC, serhii-shkodenko commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
Необязательно. Эта цена, например, может учитывать скидки или налоги. Допустим, давать 1% скидки при расчете наличными. Если эта цена является конечной ценой для заказа, то лучше назвать ее `TotalPrice`.

2021-04-18 15:12 UTC, Marynok commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
А в заказе в IList<Food> правильнее хранить оригинальный объект заказа или его копию?

2021-04-18 15:18 UTC, serhii-shkodenko commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
Я не понял вопрос.

2021-04-18 15:23 UTC, Marynok commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
Ой
А в заказе в IList<Food> правильнее хранить ссылку на оригинальный объект Food или его копию?

2021-04-18 15:39 UTC, serhii-shkodenko commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
Я по-прежнему не могу понять вопрос. Не забудь поменять `List<T>` на `IList<T>`.

2021-04-18 15:49 UTC, Marynok commented on DeliveryService/models/Order.cs
> +        public int CountItems { get; set; }
На IList уже поменяла
У производителя есть лист с объектами типа Food. При добавлении в заказ объекта типа Food нужно ссылаться на существующий или создавать новый ?

2021-04-20 19:35 UTC, serhii-shkodenko requested changes
Еще небольшое замечание и будет аппрув.

2021-04-20 19:35 UTC, serhii-shkodenko commented on DeliveryService/models/Order.cs
> +        public IList<OrderFoodData> Foods { get; set; }
Проинициализируй свойство в конструкторе:
`Foods = new List<OrderFoodData>();`

2021-04-20 19:35 UTC, serhii-shkodenko commented on DeliveryService/models/Manufacturer.cs
> +        public IList<Food> Foods { get; set; }
Проинициализируй свойство в конструкторе:
`Foods = new List<Food>();`

2021-04-20 19:51 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-04-20 19:52 UTC, merged