init lb_3
Marynok/Martyuk_Labs pull request #3
Opened 2021-04-21 14:05 UTC by Marynok

Task 3 was created

2021-04-21 21:38 UTC, serhii-shkodenko requested changes

2021-04-21 21:38 UTC, serhii-shkodenko commented on lb_3/.gitignore
> +## Ignore Visual Studio temporary files, build results, and
В солюшене уже есть .gitignore. Одного достаточно.

2021-04-21 21:38 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataBase/DeliveryDataBase.cs
> +            return (manufacturer.Count() == 0 ? null : manufacturer.First());
В Linq есть метод расширения `FirstOrDefalt()`. Он как раз решает проблему, которую ты решила, однако более элегантно. Твой тогда можно переписать так:

`return Manufacturers.Where(m => m.Name == name).FirstOrDefault();
`

или

`return Manufacturers.FirstOrDefault(m => m.Name == name);
`

Используй этот метод для всех подобных случаев в ПР.

2021-04-21 21:38 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataBase/DeliveryDataBase.cs
> +        public IList<Manufacturer> Manufacturers {get; private set; }
Ты реализовала методы доступа для этих коллекций, однако дала к ним публичный доступ. Раз ты сделала методы доступа, лучше эти свойства заменить на приватные поля.

2021-04-22 06:42 UTC, Marynok commented on lb_3/DeliveryService/DataBase/DeliveryDataBase.cs
> +        public IList<Manufacturer> Manufacturers {get; private set; }
Методы из DeliveryDataBase делают выборку по критерию, у меня есть места где нужен весь лист объектов

2021-04-24 19:41 UTC, serhii-shkodenko requested changes
В целом выглядит перспективно. Поправь пока это, мозже посмотрю еще раз.

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +            var address = SearcAddress(street, houseNumber);
Опечатка в слове "Searc".

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        public OrderFoodData CreateFoodItem(int id, int count)
Лучше в название метода добавить ..OrDefault(), чтобы просигнализировать о том, что метод может возвращать null.

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        public Model SearchModelById(Model[] models, int id)
Поиск в методе выполняется с помощью `FirstOrDefault()`, который вызывывается `IEnumerable<T>`, поэтому в параметрах метода лучше указать именно IEnumerable<T>, тогда не придется выше по стеку вызова вызывать `ToArray() `на коллекции. Просмотри, пожлауйста, весь ПР на этот счет. В целом целесообразность этого метода у меня вызывает сомнения.

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +            return (Manufacturer)SearchModelById(_dataBase.Manufacturers.ToArray(), id);
Тебе не нужо вызывать здесь метод. Просто вызывай `FirstOrDefault()` на `_dataBase.Manufacturers`, как ты делаешь в других методах.

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/BaseConsoleFunction.cs
> +        const int phoneNumberCount = 9;
Модификатор доступа здесь нужно указать.

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/BaseConsoleFunction.cs
> +        public static bool CheckAreae(string message, string expectedResponse)
Опечатка в "CheckAreae".

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/Check/Checker.cs
> +        public static int NumberCehck(string number)
Опечатка в имени метода "NumberCehck".

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        private int getId(Model[] list)
Метод расширения `Last()` вызывается на `IEnumerable<T>`, поэтому в параметрах лучше просить параметр именного такого типа. Более того, это избавит от необходимости в стеке вызовов выше вызывать `ToArray()`.

2021-04-24 19:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        private int getId(Model[] list)
Имена методов следует писать в `PascalCase`.

2021-04-25 00:41 UTC, serhii-shkodenko requested changes
В целом мне показался хорошим подход. Поправь эти замечания и будет замечательно.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceMenu.cs
> +        public ServiceMenu(MainMenu mainMenu, DataBaseController dataBaseController)
Нарушение Dependency Inversion Principle. Используй интерфейсы.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceMenu.cs
> +        public DataBaseController DataBaseController { get; private set; }
Нарушение инкапсуляции. Для обеспечения доступа классов-наследников достаточно будет модификатора 
 `protected`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceMenu.cs
> +        public MainMenu MainMenu { get; private set; }
Нарушение инкапсуляции. Для обеспечения доступа классов-наследников достаточно будет модификатора `protected`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        public DataBaseController(DeliveryDataBase dataBase)
Нарушение Dependency Inversion Principle. Используй интерфейсы.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        public Address SearcAddress(string street, string houseNumber)
Опечатка в слове "Searc".

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        public FoodType SearcFoodType(string name)
Опечатка в слове "Searc".

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        public Manufacturer SearchManufacturerById(int id)
Опечатка в слове "Searc".

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        public IList<Manufacturer> GetManufacturers()
Для создания производителя ты сделала отдельный метод. Здесь будет достаточно возвращать `IEnumerable<T>`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        public IList<OrderFoodData> GetBasketItems(Client client)
Здесь будет достаточно возвращать `IEnumerable<T>`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +    public class DataBaseController
В английском языrе "Database" - это одно слово. Поэтому заглавная буква должна быть только вначале слова. Поправь по все проекту, пожалуйста.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Basket.cs
> +        public void AddItem(OrderFoodData orderFoodData)
У тебя свойство публичное и доступно за изменений, необходимости в этом методе не вижу.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Basket.cs
> +        public void ClearItems()
У тебя свойство публичное и доступно за изменений, необходимости в этом методе не вижу.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +    public class DataBaseController
Будет идеально разделить этот класс на более мелкие, которые будут оперировать данными для каждой отдельной модели. Сейчас через класс проходит слишком много осей изменений.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Client.cs
> +        public void AddOreder(Order order)
Опечатка в имени метода.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Client.cs
> +            order.Client = this;
Я не вижу необходимости в каждый заказ созранять клиента, потому что заказы и так хранятся в свойстве модели клиента.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Client.cs
> +        public void AddOreder(Order order)
Я не вижу небходимости в этом методе, так как свйоство `Orders `публичное и доступно для записи.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/DeliveryMan.cs
> +    class DeliveryMan: Person
Не хватает модификатора доступа.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Manufacturer.cs
> +        public void AddFood(Food food)
Я не вижу необходимости в этом методе. Свойство `Foods` публичное и доступно для записи.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Manufacturer.cs
> +            food.Manufacturer = this;
Это присваивание также излишне. По тем же причинам, что и выше.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Order.cs
> +        private void setTotalPrie()
Методы именуются в C# в PascalCase.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Order.cs
> +        private void setTotalPrie()
Этот метод можно вызывать прямо в геттере свойства.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Order.cs
> +        public void AddFoods(IList<OrderFoodData> foods)
Свойств Foods публичное и доступно для записи, поэтому небходимости в этом методе нет.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Person.cs
> +        public int PhoneNumber { get; set; }
Поле `PhoneNumber` содержит скобки, поэтому для него не годится тип `int`. `string` более удачным выбором будет.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/BaseConsoleFunction.cs
> +        const int phoneNumberCount = 9;
Константы в C# именуются в `PascalCase`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/Check/Checker.cs
> +        const int phoneNumberCount = 9;
Константы в C# именуются в `PascalCase`. Не хватает модификатора доступа.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/Check/Checker.cs
> +            public static T CheckProperty(string value ,Parser parse)
Поправь, пожалуйста, форматирование. Пробел должен идти после запятой, а не до.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/Check/Checker.cs
> +            public static T CheckProperty(string value ,Parser parse)
Более привычным и ожидаемым именем параметра с типом `Parser` будет просто `parser`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/Check/Checker.cs
> +        public static int GetPropertyInt(string value)
Этот метод и все подобные нижеследующие тебе не нужны, это просто обертки над `ConsoleCheck<T>`. Вполне допустимо открыть к нему доступ и вызывать метод `CheckProperty` напрямую. Тогда ты останешься с дженериковой реализацией и не будет ее закрывать сверху обертками.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +        readonly string[] cabinetMenuItems = new string[] { "Show orders", "Create new order", "Exit" };
Не хватает модификатора доступа `private`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +        readonly string[] orderMenuItems = new string[] { "Add product", "Create order", "Exit" };
Не хватает модификатора доступа `private`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +        readonly string[] orderMenuItems = new string[] { "Add product", "Create order", "Exit" };
Поскольку ты начала именовать приватные поля через `_`, то лучше везде придерживатсья этого стиля.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +        readonly string[] cabinetMenuItems = new string[] { "Show orders", "Create new order", "Exit" };
Поскольку ты начала именовать приватные поля через `_`, то лучше везде придерживатсья этого стиля.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +        public ClientMenu(MainMenu mainMenu, DataBaseController dataBaseController) : base(mainMenu, dataBaseController)
Нарушение Dependency Inversion Principle, используй интерфейсы.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +        public override void Registr()
Опечатка в имени метода.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/MainMenu.cs
> +        private string[] menuItems = new string[] { "I am manufacturer", "I am client" };
Поскольку ты начала именовать приватные поля через `_`, то лучше везде придерживатсья этого стиля.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/MainMenu.cs
> +        private string[] menuItems = new string[] { "I am manufacturer", "I am client" };
Не хватает модификатора `readOnly`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ManufacturerMenu.cs
> +        public ManufacturerMenu(MainMenu mainMenu, DataBaseController dataBaseController) : base(mainMenu, dataBaseController)
Нарушение Dependency Inversion Principle. Используй интерфейсы.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ManufacturerMenu.cs
> +        readonly string[] cabinetMenuItems = new string[] { "Show products", "Create new product", "Exit" };
Не хватает модификатора `private`.

2021-04-25 00:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ManufacturerMenu.cs
> +        readonly string[] cabinetMenuItems = new string[] { "Show products", "Create new product", "Exit" };
Поскольку ты начала именовать приватные поля через `_`, то лучше везде придерживатсья этого стиля.

2021-04-27 11:06 UTC, serhii-shkodenko requested changes

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceController.cs
> +        public readonly IDatabaseController<Address> Addresses;
Поля крайне нежелетельно делать публичными. Переделай, пожалуйста, на свойства и скорее всего тебе хватит модификатора `protected` вместо публичного.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceController.cs
> +        public readonly IDatabaseController<Manufacturer> Manufacturers;
Поля крайне нежелетельно делать публичными. Переделай, пожалуйста, на свойства и скорее всего тебе хватит модификатора `protected` вместо публичного.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceMenu.cs
> +        private IMenu _mainMenu;
Не хватает модификатора `readonly`.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceMenu.cs
> +        protected AddressController _addressController;
Переделай на свойство, пожалуйста. Неприватный уровень доступа для полей является нежелательным и является нарушением инкапсуляции.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceMenu.cs
> +        protected ManufacturerController _manufacturerController;
Переделай на свойство, пожалуйста. Неприватный уровень доступа для полей является нежелательным и является нарушением инкапсуляции.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/ServiceController.cs
> +    public abstract class ServiceController
Очевидно, предполагалось, что от этого класса будет происходить наследование, но я не вижу, чтобы ты его использовала. Если он тебе не нужен, удали.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/AddressController.cs
> +        public readonly IDatabaseController<Address> Addresses;
Это поле должно быть приватным. Имя тогда нужно будет поменять в соовтветствии с конвенцией.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/BasketController.cs
> +        public Basket Basket;
Все поля в этом классе лучше сделать приватными и поменять имена в соответсвии с конвенцией.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/ClientController.cs
> +        public Client Client;
Все поля в этом классе лучше сделать приватными и поменять имена в соответсвии с конвенцией.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/FoodController.cs
> +        public readonly IDatabaseController<Food> Food;
Все поля в этом классе лучше сделать приватными и поменять имена в соответсвии с конвенцией.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/ManufacturerController.cs
> +        public Manufacturer Manufacturer;
Все поля в этом классе лучше сделать приватными и поменять имена в соответсвии с конвенцией.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        private IDataBase _database;
Не хватает модификатора `readonly`.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/DataBaseController.cs
> +        private IList<TModel> _models;
У тебя уже есть доступ к базе через зависимость, в этом поле нет необходимости и его можно удалить.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/IDataBase.cs
> +        public Dictionary<Type, IList> Database { get; set; }
В интерфейсах использование модификатора `public` является избыточным. Просто удали его.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +        public ClientMenu(IMenu mainMenu, ClientController clientController, BasketController basketController,
Нарушение Dependenсy inversion principle. Используй, пожалуйста, интерфейсы.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/MainMenu.cs
> +        public MainMenu(ManufacturerController manufacturerController, ClientController clientController, AddressController addressController,
Нарушение Dependenсy inversion principle. Используй, пожалуйста, интерфейсы.

2021-04-27 11:06 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ManufacturerMenu.cs
> +        public ManufacturerMenu(IMenu mainMenu, ManufacturerController manufacturerController,
Нарушение Dependenсy inversion principle. Используй, пожалуйста, интерфейсы.

2021-04-27 11:13 UTC, Marynok commented on lb_3/DeliveryService/UserInterface/ManufacturerMenu.cs
> +        public ManufacturerMenu(IMenu mainMenu, ManufacturerController manufacturerController,
На каждый контроллер нужен свой интерфейс?

2021-04-27 11:21 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ManufacturerMenu.cs
> +        public ManufacturerMenu(IMenu mainMenu, ManufacturerController manufacturerController,
Да.

2021-04-27 11:40 UTC, Marynok commented on lb_3/DeliveryService/UserInterface/MainMenu.cs
> +        public MainMenu(ManufacturerController manufacturerController, ClientController clientController, AddressController addressController,
А это вообще "нормально", передавать контроллеры вот так из класса в класс ?

2021-04-27 12:02 UTC, serhii-shkodenko requested changes

2021-04-27 12:02 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Program.cs
> +            var client = new DatabaseController<Client>(db);
Лучше назвать все эти переменные в множественном числе.

2021-04-27 12:02 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Program.cs
> +            var clientControllr = new ClientController(client, order);
Здесь и ниже проверь, пожлалуйса, написание слова `Controller`.

2021-04-27 13:03 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/MainMenu.cs
> +        public MainMenu(ManufacturerController manufacturerController, ClientController clientController, AddressController addressController,
Это вполне нормально использовать зависимости. В частности, это помагает реализации Single responsibility principle.

2021-04-27 13:08 UTC, serhii-shkodenko requested changes

2021-04-27 13:08 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/Check/Checker.cs
> +        public static int GetPropertyInt(string value)
Не забудь поправить это замечание. Я его снова активировал. Если ты со мной несогласна, лучше написать почему именно. Тогда мы может вместе подумать и выработать лучшее решение.

2021-04-27 13:11 UTC, serhii-shkodenko commented
В целом выглядит уже намного лучше. Я еще вечером склонирую ветку, посмотрю детальнее и может что-то еще напишу.

2021-04-27 15:28 UTC, Marynok commented
По поводу замечания, речь вроде бы шла о том что это не нужные методы. Просто такое решение упрощает вызов чека, и так как во многих местах одинаковые проверки, как по мне, упрощает код. Мне нравиться такое решение, я бы хотела его оставить.

2021-05-01 19:52 UTC, serhii-shkodenko requested changes
Ошибочный коммент.

2021-05-01 19:53 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-05-03 13:05 UTC, merged