init lb_5
Marynok/Martyuk_Labs pull request #5
Opened 2021-05-15 09:38 UTC by Marynok

lb_5 was created

2021-05-18 00:14 UTC, serhii-shkodenko requested changes

2021-05-18 00:14 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Program.cs
> +            var log = new DataLogger("log","txt");
Имя переменной лучше дать `logger`, лог - это либо сам файл с данными, либо сами данные.

2021-05-18 00:14 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Logger/DataLogger.cs
> +        public DataLogger(String folder, String fileType)
Используй алиасы для типов. Соответствующая рекомендация есть в четвертой редакции спецификации язые C#. То есть `string` вместо `String`.

2021-06-02 21:26 UTC, serhii-shkodenko requested changes

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/IDataLogger.cs
> +    public interface IDataLogger
Логирование и сохранение данных - это немного разные понятия и не стоит их смешивать, поэтому и интерфейс, и класс, его реализующий, лучше переименовать.

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/IDataLogger.cs
> +        void SaveChanges(String content);
Используй, пожалуйста, алиас типа, а не его полное BCL имя.

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Program.cs
> +            var logger = new DataLogger("log","txt");
Не забуть переименовать переменную, когда будешь менять имя класса.

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/FoodMenu.cs
> +        public enum Action { DELETE, UPDATE };
Вынеси, пожалуйста, enum в отдельный файл.

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/FoodMenu.cs
> +        IFoodController _foodController;
Не хватает модификаторов.

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/FoodMenu.cs
> +        IManufacturerController _manufacturerController;
Не хватает модификаторов.

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ManufacturerMenu.cs
> +        private readonly string[] _cabinetMenuItems = new string[] { "Reduct products", "Exit" };
Если под `Reduct` имеется в виду, "править", то лучше использовать слово `Edit`.

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ManufacturerMenu.cs
> +        private IMenu _foodMenu;
Модификатора `readonly` не хватает.

2021-06-02 21:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/FoodController.cs
> +            var food = _food.Search(f => f.Id == id);
Здесь лучше сократить до 
`return _food.Search(f => f.Id == id);`

2021-06-02 21:29 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/IDataLogger.cs
> +    public interface IDataLogger
Будет достаточно назвать ILogger.

2021-06-02 21:30 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/IDataLogger.cs
> +        void SaveChanges(String content);
Логер занимается логированием, поэтому метод лучше так и назвать: `void Log(string message`).

2021-06-03 22:17 UTC, serhii-shkodenko requested changes

2021-06-03 22:17 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Logger/DeliveryLogger.cs
> +            _folder = $"/{folder}";
Эта переменная у тебя статическая. Получается, что при инициализации нового объекта этого типа, ты можешь поменять ее значение, соответственно она поменяется на уровне всего класса, а не только этого созданного инстанса. Поэтому сделай эту переменную просто `readonly`.

2021-06-03 22:17 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Logger/DeliveryLogger.cs
> +            _fileType = $".{fileType}";
Эта переменная у тебя статическая. Получается, что при инициализации нового объекта этого типа, ты можешь поменять ее значение, соответственно она поменяется на уровне всего класса, а не только этого созданного инстанса. Поэтому сделай эту переменную просто `readonly`.

2021-06-03 22:17 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Logger/DeliveryLogger.cs
> +            _folder = $"/{folder}";
Эту переменную ты используешь вместе с `AppDomain.CurrentDomain.BaseDirectory`. Это свойство в конце содержит слеш/обратный слеш (в зависимости от ОС), поэтому нет нужды сохранять добавочный слеш.

2021-06-03 22:17 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Logger/DeliveryLogger.cs
> +               GetFileName()+_fileType
Раз используешь массив и передаешь его в `Path.Combine()`, то раздели эту строку на две и передай три строки в массиве, а не две.

2021-06-03 22:17 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/FoodMenu.cs
> +        private readonly string[] _chengeMenuItems = new string[] { "Select product", "Exit" };
Опечатка в слове. Нужно `change`.

2021-06-04 06:23 UTC, Marynok commented on lb_3/DeliveryService/DataController/Logger/DeliveryLogger.cs
> +               GetFileName()+_fileType
var pathParts = new[]
            {
               GetPath(),
               GetFileName(),
                _fileType
            };
Если так написать, то Path.Combine() вставит слеш между именем файла и его типом

2021-06-05 10:10 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-05 10:21 UTC, merged