Lb 6
Marynok/Martyuk_Labs pull request #6
Opened 2021-05-20 13:27 UTC by Marynok

lb_6 was created

2021-06-05 10:17 UTC, serhii-shkodenko requested changes

2021-06-05 10:17 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Abstracts/DirectoryMaker.cs
> +        public string Folder { get; set; }
Раз ты публично задаешь первоначальное задание этому свойству, может вообще убрать сеттер, или сделать его приватным?

2021-06-05 10:18 UTC, serhii-shkodenko commented
После мержа пятого в мейн, вмержи сюда мейн, я после этого гляну более детально.

2021-06-05 11:25 UTC, Marynok commented
Не совсем поняла, я правильно сделала мерж?

2021-06-05 22:42 UTC, serhii-shkodenko requested changes

2021-06-05 22:42 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/ISerializer.cs
> +    public interface ISerializer
Я предлагаю тебе переименовать интерфейс, класс, его реализующий и их методы. Суть их работы заключается в сохранения состоянии каких-то списков на диск. В каком именно виде, сериализованном ли в Json, или Xml,  находятся эти записываемые данные я бы не указывал.

2021-06-06 09:56 UTC, serhii-shkodenko requested changes
Переименуй, пожалуйста, и будет апрув.

2021-06-06 09:56 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataBase/DeliveryDataBase.cs
> +        private IDataSaver _serializer;
Упустила, что и имя переменной было бы лучше переименовать.

2021-06-06 09:56 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataBase/DeliveryDataBase.cs
> +        public DeliveryDatabase(IDataSaver serializer)
Упустила, что и имя параметра было бы лучше переименовать.

2021-06-06 09:56 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Program.cs
> +using DeliveryService.Serializer;
Неймспейс тоже нужно переименовать.

2021-06-06 09:56 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Program.cs
> +            var serializer = new DataSaver("datas");
Переименную тоже нужно переименовать.

2021-06-06 10:05 UTC, serhii-shkodenko commented
> Не совсем поняла, я правильно сделала мерж?
Если билдится и работает, значит правильно 😀.

2021-06-06 10:26 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-06-06 10:40 UTC, merged