Lb 7
Marynok/Martyuk_Labs pull request #7
Opened 2021-05-30 17:45 UTC by Marynok

Cache was created

2021-06-05 10:23 UTC, serhii-shkodenko requested changes

2021-06-05 10:23 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +        private const int MAX_SIZE = 5;
Константы именуются в `PascalCase`.

2021-06-05 10:23 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +            var thread = new Thread(() => action(secAction, model));
Не нужно использовать здесь потоки. Достаточно пложить в кеш. Подумай, нужен ли будет лок.

2021-06-12 16:41 UTC, serhii-shkodenko requested changes

2021-06-12 16:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/ManufacturerController.cs
> +             _manufacturers.Update(_manufacturer);
Лишний пробел в начале строки.

2021-06-12 16:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +        public void SetToCashe<TModel>(TModel model,IList<TModel> models) where TModel : Model
Опечатка в слове `Cache`.

2021-06-12 16:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +        public TModel Search<TModel>(Func<TModel, bool> func) where TModel : Model
Я бы переназвал на `GetFromCache(Func<TModel, bool> filter)`.

2021-06-12 16:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +        public void RemoveFromCashe<TModel>(Action<TModel, IList<TModel>> action,TModel model) where TModel : Model
Опечатка в слове `Cache`.

2021-06-12 16:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +    class ThreadSafeCache : Repository, ICache
Не хватает модификатора доступа.

2021-06-12 16:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +        public Dictionary<Type, Object> Locks { get; set; }
А зачем тебе возможность изменения словаря локов. Если не нужна, удали сеттер.

2021-06-12 16:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataBase/DeliveryDataBase.cs
> +    public class DeliveryDatabase: Repository, IDataBase
База данных - это база данных, а репозиторий - это репозиторий. Паттерн репозиторий будете проходить в одном из следущих модулей. Удали это наследование.

2021-06-12 16:41 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +    class ThreadSafeCache : Repository, ICache
Кеш не должен быть репозиторем. Удали это наследование. Паттерн будете проходить далее на курсах.

2021-06-12 17:36 UTC, Marynok commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +    class ThreadSafeCache : Repository, ICache
Я не пыталась реализовать паттерн, просто хотела избавиться от дублирования кода. Могу переименовать Repository на Storage, или если такое наследование не уместно, то могу убрать его. Как лучше?

2021-06-12 17:38 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +    class ThreadSafeCache : Repository, ICache
Кеш не может иметь доступа в базу данных. Именно наш кеш, он просто кеширует некоторые данные, поступающие из БД и обрабатываемые в бизнес слое.

2021-06-12 17:49 UTC, Marynok commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +    class ThreadSafeCache : Repository, ICache
Так он и не имеет доступа. Он же просто наследует словарь с объектами от абстрактного класса Repository.

2021-06-12 17:49 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +    class ThreadSafeCache : Repository, ICache
Он не должен этого делать.

2021-06-12 17:54 UTC, Marynok commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +    class ThreadSafeCache : Repository, ICache
Хорошо, но словарь можно оставить в кеше?

2021-06-12 17:55 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/ThreadSafeCache.cs
> +    class ThreadSafeCache : Repository, ICache
Ну, если убрать все условности, то словарь и есть кеш, так что... да, можно.

2021-07-11 15:38 UTC, serhii-shkodenko requested changes

2021-07-11 15:38 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +            var models = _cache.GetList<TModel>();
Пока ты будешь выбирать по фильтру нужные тебе значения, кеш мог устареть, поэтому оберни операции по доступу и фильтрации в лок.

2021-07-11 15:38 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +            if (models.Count > MaxSize)
Проверка количества и удаления сами по себе две атомарные операции, но вместе они не потокобезопасные. Поэтому их нужно обернуть в лок тоже.

2021-07-12 16:32 UTC, serhii-shkodenko requested changes
Поправь, плиз, эти небольшие замечания и будет апрув.

2021-07-12 16:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +        public void RemoveFromCache<TModel>(TModel model, IList<TModel> models) where TModel : Model
Как такового удаления из кеша здесь не происходит. Ты удаляешь по ключу элемент из коллекции. Поэтому лучше переназвать этот метод. Если ты хочешь прям удалить элемпент из кеша, передавай ему `Id` модели и удаляй из `ICache` объекта. Если этот метод задумывался для сокращения количества дублирующегося кода, и не предназнался для вызова извне, то тогда его нужно сделать приватным. Но я бы все аврно передавал `Id`, а не весь объект.

2021-07-12 16:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +            if (models.Count > MaxSize)
В целом не очень хорошо, что архитектура подразумевает превышение максимального количества элементов. Поправь это пожалуйста.

2021-07-12 16:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +        public void TredSafeWorkWithCache<TModel>(Action<TModel, IList<TModel>> action, TModel model) where TModel : Model
Опечатка в слове `Thread`.

2021-07-12 16:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/ICacheController.cs
> +        public void TredSafeWorkWithCache<TModel>(Action<TModel, IList<TModel>> action, TModel model) where TModel : Model;
Удали, пожалуйста, модификатор доступа. По умолчанию все члены интерфейса публичный, поэтому он опускается.

2021-07-12 16:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/ICacheController.cs
> +        public void TredSafeWorkWithCache<TModel>(Action<TModel, IList<TModel>> action, TModel model) where TModel : Model;
Опечатка в слове `Thread`.

2021-07-13 08:34 UTC, Marynok commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +        public void RemoveFromCache<TModel>(TModel model, IList<TModel> models) where TModel : Model
Этот метод вызывается извне, точнее он передается как параметр в ThredSafeWorkWithCache, и его сигнатура должна соответствовать  входным параметрам делегата. А так как предполагается что в ThredSafeWorkWithCache может передаваться как RemoveFromCache так и SetToCache, то набор входных параметров делегата должен подходит для двух методов.

2021-08-23 08:45 UTC, serhii-shkodenko requested changes
Поправь, пожалуйста, эти описки и будет апрув.

2021-08-23 08:45 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Program.cs
> +            var cashe = new DeliveryCache();
Описка. Нужно `cache`.

2021-08-23 08:45 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Program.cs
> +            var cashController = new CacheController(cashe);
Описка. Нужно `cache`.

2021-08-23 09:59 UTC, serhii-shkodenko commented on lb_3/DeliveryService/DataController/Cache/CacheController.cs
> +        public void RemoveFromCache<TModel>(TModel model, IList<TModel> models) where TModel : Model
Ок, принимается. Однако, такое решение в будущем может привести к проблемам. И `RemoveFromCache()` и `SetToCache()` - это публичные методы, и они, как можно представить, будут вызваны вне твоего `ThredSafeWorkWithCache()` контекста. И это приведет к поведению, которое не ожидается, или даже исключениям. Лучше избегать такой неоднозначности.

2021-08-29 01:40 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-08-30 04:23 UTC, merged