init lb_8
Marynok/Martyuk_Labs pull request #8
Opened 2021-06-12 14:45 UTC by Marynok

init currency exchange rate

2021-06-14 14:32 UTC, serhii-shkodenko requested changes

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/CurrencyController.cs
> +        private string getDate()
Имена методов записываются в `PascalCase`.

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/CurrencyController.cs
> +            return DateTime.Now.ToShortDateString();
Для этого я бы не делал одтельного метода. Удали, пожалуйста.

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/CurrencyController.cs
> +            return (exchangeRate is null)? 0 : exchangeRate.Sale ;
Я думаю скобки можно удалить.

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Controllers/CurrencyController.cs
> +            if ((_currency is null) || (!_currency.Date.Equals(getDate())))
Я думаю скобки можно удалить.

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/ICurrencyController.cs
> +        public Task<Currency> GetApiDataAsync();
В интерфейсах модификатор `public` опускается.

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Interfaces/ICurrencyController.cs
> +        public Task<decimal> GetExchangeRate(string searchCurrency);
В интерфейсах модификатор `public` опускается.

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Currency.cs
> +        public string Date { get; set; }
Это поле разве не деcериализуетя в `DateTime`?

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/Models/Currency.cs
> +        public string BaseCurrencyLit { get; set; }
Раз ты используешь `JsonPropertyName` атрибут, у тебя есть возможность задать человеческое имя для этого свойства.

2021-06-14 14:32 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +                    ShowOrderPrice();
Поскольку у тебя этот метод `async void`, то выполненение программы после негопродолжается в синхронном режиме, то есть до того как будут получены результаты с внешнего сервиса. Нужно использовать `await`.

2021-06-15 19:31 UTC, Marynok commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +                    ShowOrderPrice();
Не совсем понимаю..  так ведь пользователь будет ожидать ответ от сервера . У меня “бронируется “ место для информации о цене в другой валюте, то есть где попало оно не выведется, оно может вывестись не вовремя, но я думала добавить чекер на проверку актуально ли выводить данную информацию.

2021-08-23 09:26 UTC, serhii-shkodenko requested changes

2021-08-23 09:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +        public async void ShowOrderPrice()
Да, C# позволяет писать `async` `void` методы, но у них есть специальное узкое место для использования - асинхронные обработчки событий. Во всех остальных случаях при работе с асинхронным кодом нужно возвращать `Task`, `Task<T>`, `ValueTask` или `ValueTask<T>`.

2021-08-23 09:26 UTC, serhii-shkodenko commented on lb_3/DeliveryService/UserInterface/ClientMenu.cs
> +                    ShowOrderPrice();
> “бронируется “ место для информации о цене в другой валюте, то есть где попало оно не выведется

Результат работы метода ShowOrderPrice() как раз и выведется, где попало. Потому что ты не ждешь его завершения.

> Не совсем понимаю.. так ведь пользователь будет ожидать ответ от сервера.

Если ты беспокоишься о сетевой задержке, то ты ее не избежишь вовсе. В принципе, для того чтобы минимизировать влияние ее на всех пользователей, здесь мог бы пригодиться механизм кеширования, поскольку курс валют меняется раз в сутки. То есть условно, можно один раз его получить в сутки, а потом все время читать из кеша. Но это не в рамках этого задания.

2021-08-29 00:49 UTC, serhii-shkodenko approved these changes
На мой коммент по поводу десериализации данных в тип `DateTime` вместо `string` ты не ответила, однако его зарезолвила. Я посмотрел исходный json, который присылается АПИ, дата там действительно не соответствует ISO 8601:
![Screenshot 2021-08-28 184620](https://user-images.githubusercontent.com/69808191/131234547-93adbea8-8e3d-4c0f-864b-1c0bc3db54a3.jpg)

Чтобы десериализовать такие данные нужно использовать класс `JsonConverter<T>` из пространства `System.Text.Json`: 

![Screenshot 2021-08-29 033957](https://user-images.githubusercontent.com/69808191/131234570-a709578f-269c-4820-aabc-35302d95bcb2.jpg)

В остальном все хорошо, можно мержить.

2021-08-29 06:56 UTC, Marynok commented
Случайно пропустила этот комментарий, спасибо что сказал и показал решение.
Я добавила конвертер.

2021-08-29 12:26 UTC, serhii-shkodenko approved these changes
Отлично, можно мержить.

2021-08-30 05:04 UTC, merged